DROP TABLE IF EXISTS item;

CREATE TABLE item (
id INT AUTO_INCREMENT  PRIMARY KEY,
name VARCHAR(150) NOT NULL,
description VARCHAR(1000),
cost INT NOT NULL,
type VARCHAR(50)
);

DROP TABLE IF EXISTS students;

CREATE TABLE students (
id INT AUTO_INCREMENT  PRIMARY KEY,
name VARCHAR(150) NOT NULL,
surname VARCHAR(150) NOT NULL,
role VARCHAR(50) NOT NULL,
passwordhash VARCHAR(150) NOT NULL,
email VARCHAR(150) NOT NULL,
balance INT NOT NULL,
earnings INT NOT NULL
);